// Auto-generated by build_label_preload.py -- do not hand-edit.
// Seeds label_tool.html's floor5 with the existing normal-lens ground truth.
window.LABEL_PRELOAD = window.LABEL_PRELOAD || {};
window.LABEL_PRELOAD.floor5 = {
  "nextSeq": 20,
  "points": [
    {
      "id": "seed-p01",
      "seq": 1,
      "x": 206.31,
      "y": 108.64,
      "heading": "",
      "room": "",
      "notes": "หน้าห้องน้ำ",
      "stem": "p01",
      "images": [
        {
          "filename": "p01_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p01_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p01_normal_backward.jpg"
        },
        {
          "filename": "p01_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p01_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p01_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p02",
      "seq": 2,
      "x": 206.31,
      "y": 216.3,
      "heading": "",
      "room": "509",
      "notes": "",
      "stem": "p02",
      "images": [
        {
          "filename": "p02_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p02_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p02_normal_forward.jpg"
        },
        {
          "filename": "p02_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p02_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p02_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p02b",
      "seq": 3,
      "x": 217.72,
      "y": 226.62,
      "heading": "",
      "room": "509",
      "notes": "ประตูซ้าย",
      "stem": "p02b",
      "images": [
        {
          "filename": "p02b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p02b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p02b_normal_forward.jpg"
        },
        {
          "filename": "p02b_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p02b_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p02b_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p03",
      "seq": 4,
      "x": 206.31,
      "y": 153.38,
      "heading": "",
      "room": "510",
      "notes": "",
      "stem": "p03",
      "images": [
        {
          "filename": "p03_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p03_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p03_normal_backward.jpg"
        },
        {
          "filename": "p03_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p03_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p03_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p04",
      "seq": 5,
      "x": 206.31,
      "y": 273.4,
      "heading": "",
      "room": "508",
      "notes": "",
      "stem": "p04",
      "images": [
        {
          "filename": "p04_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p04_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p04_normal_backward.jpg"
        },
        {
          "filename": "p04_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p04_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p04_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p04b",
      "seq": 6,
      "x": 206.31,
      "y": 292.62,
      "heading": "",
      "room": "507",
      "notes": "",
      "stem": "p04b",
      "images": [
        {
          "filename": "p04b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p04b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p04b_normal_forward.jpg"
        },
        {
          "filename": "p04b_normal_forward_2.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p04b_normal_forward_2.jpg",
          "relpath": "label_image/label_floor5/p04b_normal_forward_2.jpg"
        }
      ]
    },
    {
      "id": "seed-p05",
      "seq": 7,
      "x": 206.31,
      "y": 351.46,
      "heading": "",
      "room": "506",
      "notes": "",
      "stem": "p05",
      "images": [
        {
          "filename": "p05_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p05_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p05_normal_forward.jpg"
        },
        {
          "filename": "p05_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p05_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p05_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p05b",
      "seq": 8,
      "x": 206.31,
      "y": 369.52,
      "heading": "",
      "room": "505",
      "notes": "",
      "stem": "p05b",
      "images": [
        {
          "filename": "p05b_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p05b_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p05b_normal_backward.jpg"
        },
        {
          "filename": "p05b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p05b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p05b_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p06",
      "seq": 9,
      "x": 206.31,
      "y": 427.2,
      "heading": "",
      "room": "504",
      "notes": "",
      "stem": "p06",
      "images": [
        {
          "filename": "p06_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p06_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p06_normal_backward.jpg"
        },
        {
          "filename": "p06_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p06_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p06_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p06b",
      "seq": 10,
      "x": 206.31,
      "y": 445.81,
      "heading": "",
      "room": "503",
      "notes": "",
      "stem": "p06b",
      "images": [
        {
          "filename": "p06b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p06b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p06b_normal_forward.jpg"
        },
        {
          "filename": "p06b_normal_forward_2.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p06b_normal_forward_2.jpg",
          "relpath": "label_image/label_floor5/p06b_normal_forward_2.jpg"
        }
      ]
    },
    {
      "id": "seed-p06c",
      "seq": 11,
      "x": 206.31,
      "y": 460.15,
      "heading": "",
      "room": "",
      "notes": "หน้าห้องน้ำ",
      "stem": "p06c",
      "images": [
        {
          "filename": "p06c_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p06c_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p06c_normal_backward.jpg"
        },
        {
          "filename": "p06c_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p06c_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p06c_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p07",
      "seq": 12,
      "x": 293.7,
      "y": 427.68,
      "heading": "",
      "room": "534",
      "notes": "",
      "stem": "p07",
      "images": [
        {
          "filename": "p07_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p07_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p07_normal_forward.jpg"
        },
        {
          "filename": "p07_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p07_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p07_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p07b",
      "seq": 13,
      "x": 293.7,
      "y": 448.78,
      "heading": "",
      "room": "533",
      "notes": "",
      "stem": "p07b",
      "images": [
        {
          "filename": "p07b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p07b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p07b_normal_forward.jpg"
        },
        {
          "filename": "p07b_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p07b_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p07b_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p08",
      "seq": 14,
      "x": 293.7,
      "y": 350.3,
      "heading": "",
      "room": "536",
      "notes": "",
      "stem": "p08",
      "images": [
        {
          "filename": "p08_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p08_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p08_normal_forward.jpg"
        },
        {
          "filename": "p08_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p08_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p08_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p08b",
      "seq": 15,
      "x": 293.7,
      "y": 369.06,
      "heading": "",
      "room": "535",
      "notes": "",
      "stem": "p08b",
      "images": [
        {
          "filename": "p08b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p08b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p08b_normal_forward.jpg"
        },
        {
          "filename": "p08b_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p08b_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p08b_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p09",
      "seq": 16,
      "x": 293.7,
      "y": 274.1,
      "heading": "",
      "room": "538",
      "notes": "531-538",
      "stem": "p09",
      "images": [
        {
          "filename": "p09_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p09_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p09_normal_backward.jpg"
        },
        {
          "filename": "p09_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p09_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p09_normal_forward.jpg"
        }
      ]
    },
    {
      "id": "seed-p09b",
      "seq": 17,
      "x": 293.7,
      "y": 292.27,
      "heading": "",
      "room": "537",
      "notes": "",
      "stem": "p09b",
      "images": [
        {
          "filename": "p09b_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p09b_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p09b_normal_forward.jpg"
        },
        {
          "filename": "p09b_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p09b_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p09b_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p10",
      "seq": 18,
      "x": 293.7,
      "y": 244.2,
      "heading": "",
      "room": "",
      "notes": "ทางเลี้ยว",
      "stem": "p10",
      "images": [
        {
          "filename": "p10_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p10_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p10_normal_forward.jpg"
        },
        {
          "filename": "p10_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p10_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p10_normal_backward.jpg"
        }
      ]
    },
    {
      "id": "seed-p11",
      "seq": 19,
      "x": 249.96,
      "y": 231.89,
      "heading": "",
      "room": "",
      "notes": "ประตูขวา",
      "stem": "p11",
      "images": [
        {
          "filename": "p11_normal_backward.jpg",
          "lens": "normal",
          "direction": "backward",
          "url": "label_image/label_floor5/p11_normal_backward.jpg",
          "relpath": "label_image/label_floor5/p11_normal_backward.jpg"
        },
        {
          "filename": "p11_normal_forward.jpg",
          "lens": "normal",
          "direction": "forward",
          "url": "label_image/label_floor5/p11_normal_forward.jpg",
          "relpath": "label_image/label_floor5/p11_normal_forward.jpg"
        }
      ]
    }
  ]
};
