"""Seed label_tool.html with the real, already-labeled floor5 ground truth.

Reads visualize/data/test-queries/label_floor5/ground_truth_floor5.json (the
existing normal-lens capture set), groups rows by physical position (not by
point_group text alone -- see note below), copies+renames each image into
evidence/label_image/label_floor5/ as "<stem>_normal_<direction>.jpg", and
writes preload-floor5.js: a plain <script> (not fetched JSON, so it loads
from file://) that label_tool.html merges in automatically the first time
floor5 is opened with no local session yet.

Why group by (x_px, y_px) instead of trusting point_group verbatim: the real
ground_truth_floor5.json reuses point_group "P04" for two rows that are NOT
at the same position (508 at y=273.40 and 507 at y=292.62) -- a labeling slip
upstream. Our tool's contract is "1 point = 1 shared (x,y)", so splitting by
coordinate is the safe interpretation; point_group is kept only as the stem
the tool's filename-matching heuristic keys off of (disambiguated a/b/c on
that kind of split) so new *_wide.jpg shots the user adds later still
auto-attach to the right point.
"""

from __future__ import annotations

import json
import shutil
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC_DIR = REPO.parent / "visualize" / "data" / "test-queries" / "label_floor5"
SRC_JSON = SRC_DIR / "ground_truth_floor5.json"
OUT_DIR = Path(__file__).resolve().parent / "label_image" / "label_floor5"
OUT_JS = OUT_DIR / "preload-floor5.js"


def slug(text: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in text.strip().lower()).strip("_") or "p"


def main() -> None:
    labels = json.loads(SRC_JSON.read_text(encoding="utf-8"))["labels"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    groups: dict[tuple[float, float], list[dict]] = defaultdict(list)
    for row in labels:
        key = (round(float(row["x_px"]), 2), round(float(row["y_px"]), 2))
        groups[key].append(row)

    # Stable point order: by point_group text, then position, matches the
    # original walk order well enough and keeps seq numbers reproducible.
    ordered = sorted(groups.items(), key=lambda kv: (kv[1][0]["point_group"], kv[0]))

    stem_seen: dict[str, int] = {}
    points = []
    copied = skipped = 0
    for seq, ((x, y), rows) in enumerate(ordered, start=1):
        base_stem = slug(rows[0]["point_group"])
        n = stem_seen.get(base_stem, 0)
        stem = base_stem if n == 0 else f"{base_stem}{chr(ord('a') + n)}"
        stem_seen[base_stem] = n + 1

        images = []
        name_seen: dict[str, int] = {}
        for row in rows:
            direction = row.get("direction") or "shot"
            base_name = f"{stem}_normal_{direction}"
            k = name_seen.get(base_name, 0)
            name_seen[base_name] = k + 1
            filename = f"{base_name}.jpg" if k == 0 else f"{base_name}_{k + 1}.jpg"

            src = SRC_DIR / row["image_path"]
            if not src.exists():
                print(f"[skip] missing source image: {src}")
                skipped += 1
                continue
            shutil.copy2(src, OUT_DIR / filename)
            copied += 1
            # These files really sit on disk next to label_tool.html, so point
            # straight at them -- no File-picker gesture needed just to see the
            # old dataset's real photos. relpath doubles as the CSV image_path.
            relpath = f"label_image/label_floor5/{filename}"
            images.append({
                "filename": filename, "lens": "normal", "direction": row.get("direction") or "",
                "url": relpath, "relpath": relpath,
            })

        if not images:
            continue
        rooms = [r["room"] for r in rows if r.get("room")]
        notes = list(dict.fromkeys(n for r in rows if (n := r.get("notes"))))  # unique, order-preserving
        points.append({
            "id": f"seed-{stem}", "seq": seq, "x": x, "y": y, "heading": "",
            "room": rooms[0] if rooms else "", "notes": "; ".join(notes),
            "stem": stem, "images": images,
        })

    payload = {"nextSeq": len(points) + 1, "points": points}
    OUT_JS.write_text(
        "// Auto-generated by build_label_preload.py -- do not hand-edit.\n"
        "// Seeds label_tool.html's floor5 with the existing normal-lens ground truth.\n"
        "window.LABEL_PRELOAD = window.LABEL_PRELOAD || {};\n"
        f"window.LABEL_PRELOAD.floor5 = {json.dumps(payload, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"copied {copied} images, skipped {skipped}, wrote {len(points)} points -> {OUT_JS}")


if __name__ == "__main__":
    main()
